export const data = {
    openings: [
        'I don’t want to offend anyone, but',
        'it is not an exaggeration to state that',
        'since we are on the topic,',
        'there is no denying that',
    ],
    employees: [
        'Alex',
        'Alice',
        'Daniel',
        'George',
    ],
    employeeTraits: [
        'competence',
        'conflict resolution style',
        'decision-making ability',
        'independence',
        'motivation',
        'precision',
        'problem-solving',
        'stress tolerance',
        'time management',
    ],
    discourseMarkers: [
        'by all accounts',
        'frankly',
        'generally speaking',
        'in all honesty',
        'one could say',
        'recently',
        'so to speak',
        'to put it kindly',
        'truth be told',
    ],
    negativeQualifiers: [
        'absurd',
        'beyond good taste',
        'dead end',
        'horrible',
        'miserable',
        'scandalous',
        'sorrowful',
        'unacceptable',
    ],
    workplaceSituations: [
        'disguised as work',
        'during meetings',
        'during voluntary overtime',
        'framed as a corporate meeting',
        'in the name of work',
        'under the pretext of meetings',
        'while smoking',
        'with male colleagues',
    ],
    actionVerbs: [
        'delivering',
        'directing',
        'performing',
        'presenting',
    ],
    incapacityReasons: [
        'cannot concentrate sufficiently to',
        'cannot focus well enough to',
        'comes in too late to',
        'is currently too scattered to',
        'is not emotionally ready to',
        'is too rarely present to',
        'lacks sufficient experience to',
    ],
    responsibilities: [
        'develop applications',
        'dress appropriately',
        'greet colleagues',
        'manage IT infrastructure',
        'not lose the company laptop',
        'operate the microwave',
        'set up Teams meetings',
        'use the access card',
        'work independently',
    ],
    closures: [
        'A disgrace!',
        'Disappointing...',
        'Disheartening...',
        'Laughable!',
        'Outrageous!',
        'Ridiculous!',
        'Unbelievable...',
        'What’s next?!',
        'Where are we living?!',
    ]
};
