export const data = {
    openings: [
        'I don’t want to offend anyone, but',
        'as a side note,',
        'for clarity,',
        'it cannot go unmentioned that',
        'it has become apparent that',
        'it has to be said that',
        'it is fair to say that',
        'it is increasingly clear that',
        'it is not an exaggeration to state that',
        'it is only reasonable to state that',
        'it is worth pointing out that',
        'it must be said that',
        'it should be noted that',
        'let’s just say that',
        'let’s not beat around the bush,',
        'may I remark that',
        'not to exaggerate, but',
        'quietly speaking,',
        'since we are on the topic,',
        'there is no denying that',
        'there is reason to believe that',
        'we should not overlook that',
        'why is it that',
        'without any ill intent, I must say that',
    ],
    employees: [
        'Alex',
        'Alice',
        'Daniel',
        'George',
        'Grace',
        'Jane',
        'John',
        'Sarah',
    ],
    employeeTraits: [
        'adaptability',
        'analytical thinking',
        'attitude toward feedback',
        'behavior',
        'communication',
        'competence',
        'conflict resolution style',
        'customer orientation',
        'decision-making ability',
        'efficiency',
        'flexibility',
        'independence',
        'loyalty',
        'motivation',
        'precision',
        'proactiveness',
        'problem-solving',
        'professional expertise',
        'professional humility',
        'professionalism',
        'punctuality',
        'quality of work',
        'reliability',
        'resilience',
        'sense of responsibility',
        'stress tolerance',
        'systems thinking',
        'time management',
        'willingness to cooperate',
        'willingness to learn',
        'work ethic',
    ],
    discourseMarkers: [
        'as far as I can tell',
        'by all accounts',
        'frankly',
        'from what I observe',
        'generally speaking',
        'honestly speaking',
        'if I may put it this way',
        'in all honesty',
        'in my view',
        'one could say',
        'recently',
        'so to speak',
        'strictly speaking',
        'technically speaking',
        'to be honest',
        'to be perfectly honest',
        'to put it kindly',
        'to put it mildly',
        'truth be told',
    ],
    negativeQualifiers: [
        'absurd',
        'below all standards',
        'beyond good taste',
        'beyond repair',
        'dead end',
        'depressing',
        'disappointing',
        'disgraceful',
        'disturbing',
        'embarrassing',
        'hopeless',
        'horrible',
        'inexcusable',
        'infuriating',
        'laughable',
        'low-tier',
        'miserable',
        'painfully weak',
        'pathetic',
        'pitiful',
        'revolting',
        'ridiculous',
        'scandalous',
        'shameful',
        'sorrowful',
        'terrible',
        'the lowest of the low',
        'tragic',
        'trash',
        'unacceptable',
        'unbearable',
        'unworthy of a human',
        'utterly shameful',
    ],
    workplaceSituations: [
        'disguised as a break',
        'disguised as work',
        'during bathroom breaks',
        'during coffee breaks',
        'during lunch',
        'during meetings',
        'during office entry procedures',
        'during system outages',
        'during voluntary overtime',
        'five minutes after arrival',
        'framed as a corporate meeting',
        'in the name of efficiency',
        'in the name of work',
        'regarding dress code',
        'under the excuse of team building',
        'under the guise of productivity',
        'under the pretext of meetings',
        'when assigning tasks',
        'while on the phone',
        'while smoking',
        'with female colleagues',
        'with male colleagues',
        'without managerial presence',
    ],
    actionVerbs: [
        'committing',
        'delivering',
        'directing',
        'mucking around',
        'performing',
        'presenting',
    ],
    incapacityReasons: [
        'cannot commit to',
        'cannot concentrate sufficiently to',
        'cannot focus well enough to',
        'cannot handle the workload to',
        'comes in too late to',
        'does not devote enough attention to',
        'does not possess the necessary skills to',
        'has not matured enough to',
        'is currently too scattered to',
        'is incapable of',
        'is mentally unable to',
        'is not emotionally ready to',
        'is not in a position to',
        'is not in the right condition to',
        'is not mature enough mentally to',
        'is not mentally prepared to',
        'is not motivated enough to',
        'is not well prepared to',
        'is too frequently absent to',
        'is too rarely present to',
        'is too unstable to',
        'lacks sufficient experience to',
    ],
    responsibilities: [
        'arrive on time',
        'be relied upon for anything',
        'be trusted',
        'develop applications',
        'distinguish USB drives from coffee pods',
        'distinguish colleagues from visitors',
        'dress appropriately',
        'follow basic etiquette rules',
        'greet colleagues',
        'handle paper shortages in the printer',
        'manage IT infrastructure',
        'manage servers',
        'not lose the company laptop',
        'not sign contracts on behalf of others',
        'not stand confused in front of the elevator',
        'operate the coffee machine',
        'operate the microwave',
        'reply on company chat',
        'respect working hours',
        'set up Teams meetings',
        'understand instructions given',
        'understand why unplugging servers is bad',
        'use the access card',
        'use the company dishwasher independently',
        'use the toilet properly',
        'work independently',
    ],
    closures: [
        'A disgrace!',
        'Disappointing...',
        'Disheartening...',
        'Have we learned nothing?',
        'How did we get here?',
        'How is this possible?!',
        'I cannot believe it...',
        'Is this really acceptable?!',
        'Is this really okay?!',
        'Laughable!',
        'Outrageous!',
        'Ridiculous!',
        'Sad!',
        'This cannot be serious?!',
        'Unbelievable!',
        'Unbelievable...',
        'What’s next?!',
        'Where are we living?!',
    ]
};
